name: microservice
registry: docker.io
services:
- name: backend
  project: backend\backend.csproj
- name: frontend
  project: frontend\frontend.csproj
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}"
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
- name: azurite
  image: mcr.microsoft.com/azure-storage/azurite
  args: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
  bindings:
  - port: 10000